"""Generate print-ready StancePro business cards.

Front: brand lockup + name/title/contact + vCard QR (bottom-right)
Back:  brand lockup centered + smart-link QR (stance-pro.com/download)

Output: flat PNG at 300 DPI (3.5" x 2" trim = 1050 x 600 px)
        — add 3mm bleed (+36 px each side) at the printer if required.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import qrcode
from qrcode.constants import ERROR_CORRECT_M
from PIL import Image, ImageDraw, ImageFont

import wordmark_michroma_v5 as wm_v5
from brand_logos import LOGO_DARK, LOGO_LIGHT

# ---------------- paths & constants ----------------

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE / "print_ready"
OUT_DIR.mkdir(parents=True, exist_ok=True)

DPI = 300
CARD_W = int(3.5 * DPI)   # 1050
CARD_H = int(2.0 * DPI)   # 600
MARGIN = 60               # ~5mm safe margin
LOCKUP_SIZE_SCALE = 0.8   # logo + wordmark 20% smaller
LOCKUP_GAP = 8            # horizontal gap hex → wordmark (was 24)
FRONT_WORDMARK_SCALE = 1.2   # front wordmark +20%
BACK_LOCKUP_SCALE = 0.64     # back logo + wordmark vs front (−20% × −20%)

# brand colors
NAVY = (26, 46, 97)
WHITE = (255, 255, 255)
BLUE_LIGHT_ACCENT = (0, 122, 230)     # used on white background
BLUE_DARK_ACCENT = (63, 169, 245)     # used on navy background
MUTED_NAVY = (26, 46, 97, 153)        # ~60% navy for "BY JC KRAFT" on white
MUTED_WHITE = (255, 255, 255, 178)    # ~70% white for "BY JC KRAFT" on navy

# brand assets — see brand_logos.py (generated by build_stancepro_logo_from_crystal.py)

# fonts (macOS system)
FONT_AVENIR = "/System/Library/Fonts/Avenir Next.ttc"
FONT_AVENIR_COND = "/System/Library/Fonts/Avenir Next Condensed.ttc"

# Avenir Next.ttc face indices (verified on this macOS install):
#   0 Bold, 1 BoldItalic, 2 DemiBold, 3 DemiBoldItalic, 4 Italic, 5 Medium,
#   6 MediumItalic, 7 Regular, 8 Heavy, 9 HeavyItalic, 10 UltraLight, 11 UltraLightItalic
AV_REG = 7
AV_MED = 5
AV_DEMI = 2
AV_BOLD = 0
AV_HEAVY = 8


def load_font(path: str, size: int, index: int = 0) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(path, size=size, index=index)


# ---------------- data ----------------

@dataclass(frozen=True)
class Person:
    slug: str
    name: str
    title: str
    email: str
    phone_pretty: str   # for display ("+65 9170 5866")
    phone_vcard: str    # for vCard (no spaces, "+6591705866")
    website: str = "stance-pro.com"


PEOPLE = [
    Person(
        slug="jae",
        name="Jae H. Cho",
        title="FOUNDER",
        email="jae.cho@stance-pro.com",
        phone_pretty="+65 9170 5866",
        phone_vcard="+6591705866",
    ),
    Person(
        slug="richie",
        name="Richie Johnston",
        title="CO-FOUNDER / CBO",
        email="richie.johnston@stance-pro.com",
        phone_pretty="+64 21 515 978",
        phone_vcard="+6421515978",
    ),
    Person(
        slug="dan",
        name="Dan Yap",
        title="COO",
        email="dan.yap@stance-pro.com",
        phone_pretty="+65 8118 9592",
        phone_vcard="+6581189592",
    ),
]

SMART_DOWNLOAD_URL = "https://stance-pro.com/d"


# ---------------- helpers ----------------

def vcard_payload(p: Person) -> str:
    # split N: family;given;;;
    parts = p.name.rsplit(" ", 1)
    given = parts[0] if len(parts) > 1 else p.name
    family = parts[1] if len(parts) > 1 else ""
    return (
        "BEGIN:VCARD\r\n"
        "VERSION:3.0\r\n"
        f"N:{family};{given};;;\r\n"
        f"FN:{p.name}\r\n"
        "ORG:StancePro\r\n"
        f"TITLE:{p.title.title().replace('/', ' / ')}\r\n"
        f"EMAIL;TYPE=WORK:{p.email}\r\n"
        f"TEL;TYPE=CELL:{p.phone_vcard}\r\n"
        f"URL:https://{p.website}\r\n"
        "END:VCARD\r\n"
    )


def make_qr(data: str, size_px: int, dark: tuple[int, int, int], light: tuple[int, int, int]) -> Image.Image:
    qr = qrcode.QRCode(
        version=None,
        error_correction=ERROR_CORRECT_M,
        box_size=10,
        border=2,   # quiet zone (modules)
    )
    qr.add_data(data)
    qr.make(fit=True)
    img = qr.make_image(fill_color=dark, back_color=light).convert("RGBA")
    return img.resize((size_px, size_px), Image.LANCZOS)


def paste_centered_v(
    base: Image.Image,
    overlay: Image.Image,
    x: int,
    target_h: int,
    center_y: int,
) -> tuple[int, int, int, int]:
    """Resize overlay to target_h preserving aspect, paste at (x, center_y - h/2). Returns bbox."""
    ow, oh = overlay.size
    new_w = int(ow * (target_h / oh))
    resized = overlay.resize((new_w, target_h), Image.LANCZOS)
    y = center_y - target_h // 2
    base.paste(resized, (x, y), resized)
    return (x, y, x + new_w, y + target_h)


def paste_logo_content_left(
    base: Image.Image,
    overlay: Image.Image,
    left_x: int,
    target_content_h: int,
    center_y: int,
) -> tuple[int, int, int, int]:
    """Paste logo mark with opaque content left edge flush to left_x."""
    overlay = overlay.convert("RGBA")
    bbox = overlay.getbbox()
    if not bbox:
        bbox = (0, 0, overlay.width, overlay.height)
    content = overlay.crop(bbox)
    cw, ch = content.size
    new_h = target_content_h
    new_w = max(1, int(round(cw * (new_h / ch))))
    rs = content.resize((new_w, new_h), Image.LANCZOS)
    y = center_y - new_h // 2
    base.paste(rs, (left_x, y), rs)
    return (left_x, y, left_x + new_w, y + new_h)


def draw_letterspaced(
    draw: ImageDraw.ImageDraw,
    pos: tuple[int, int],
    text: str,
    font: ImageFont.FreeTypeFont,
    fill,
    extra_spacing_px: int = 2,
) -> int:
    """Draw uppercase text with extra spacing between glyphs. Returns total width drawn."""
    x, y = pos
    start_x = x
    for ch in text:
        draw.text((x, y), ch, font=font, fill=fill)
        ch_w = font.getlength(ch)
        x += int(ch_w) + extra_spacing_px
    return x - start_x


# ---------------- front ----------------

def render_front(p: Person, dark: bool) -> Image.Image:
    bg = NAVY if dark else WHITE
    fg = WHITE if dark else NAVY
    accent = BLUE_DARK_ACCENT if dark else BLUE_LIGHT_ACCENT
    muted = MUTED_WHITE if dark else MUTED_NAVY

    card = Image.new("RGBA", (CARD_W, CARD_H), bg + (255,))
    draw = ImageDraw.Draw(card)

    # ----- top lockup: hexagon + STANCEPRO + BY JC KRAFT -----
    logo_path = LOGO_DARK if dark else LOGO_LIGHT
    logo = Image.open(logo_path).convert("RGBA")

    HEX_H = int(round(150 * LOCKUP_SIZE_SCALE))
    LOCKUP_CENTER_Y = MARGIN + HEX_H // 2
    hex_bbox = paste_logo_content_left(card, logo, MARGIN, HEX_H, LOCKUP_CENTER_Y)

    WORDMARK_H = int(round(
        wm_v5.wordmark_height_for_hex_bbox(hex_bbox, Path(logo_path)) * FRONT_WORDMARK_SCALE
    ))
    max_wm_w = CARD_W - MARGIN - hex_bbox[2] - LOCKUP_GAP
    wordmark = wm_v5.render_wordmark(dark=dark, target_h=WORDMARK_H, max_w=max_wm_w)
    wm_bbox = wm_v5.paste_wordmark(card, wordmark, hex_bbox[2] + LOCKUP_GAP, LOCKUP_CENTER_Y)

    # BY JC KRAFT under the wordmark, left-aligned to the "S"
    by_font = load_font(FONT_AVENIR, 16, AV_MED)
    by_x = wm_bbox[0]
    by_y = wm_bbox[3] + 8
    draw_letterspaced(draw, (by_x, by_y), "BY JC KRAFT", by_font, muted, extra_spacing_px=4)

    # ----- bottom-left contact block -----
    contact_left = MARGIN
    contact_top = 300

    name_font = load_font(FONT_AVENIR, 38, AV_DEMI)
    title_font = load_font(FONT_AVENIR, 18, AV_MED)
    body_font = load_font(FONT_AVENIR, 22, AV_REG)

    draw.text((contact_left, contact_top), p.name, font=name_font, fill=fg)
    title_y = contact_top + 50
    draw_letterspaced(draw, (contact_left, title_y), p.title, title_font, accent, extra_spacing_px=3)

    body_y = title_y + 50
    line_gap = 32
    draw.text((contact_left, body_y), p.email, font=body_font, fill=fg)
    draw.text((contact_left, body_y + line_gap), p.phone_pretty, font=body_font, fill=fg)
    draw.text((contact_left, body_y + line_gap * 2), p.website, font=body_font, fill=fg)

    # ----- bottom-right vCard QR -----
    qr_dark_color = WHITE if dark else NAVY
    qr_light_color = NAVY if dark else WHITE
    QR_SIZE = 220
    qr_img = make_qr(vcard_payload(p), QR_SIZE, qr_dark_color, qr_light_color)
    qr_x = CARD_W - MARGIN - QR_SIZE
    qr_y = CARD_H - MARGIN - QR_SIZE
    card.paste(qr_img, (qr_x, qr_y), qr_img)

    # tiny "SAVE CONTACT" label above QR
    label_font = load_font(FONT_AVENIR, 14, AV_MED)
    label_text = "SAVE CONTACT"
    label_w = draw.textlength(label_text, font=label_font) + (len(label_text) - 1) * 2
    label_x = qr_x + (QR_SIZE - int(label_w)) // 2
    label_y = qr_y - 22
    draw_letterspaced(draw, (label_x, label_y), label_text, label_font, muted, extra_spacing_px=2)

    return card.convert("RGB")


# ---------------- back ----------------

def render_back(dark: bool) -> Image.Image:
    bg = NAVY if dark else WHITE
    fg = WHITE if dark else NAVY
    accent = BLUE_DARK_ACCENT if dark else BLUE_LIGHT_ACCENT
    muted = MUTED_WHITE if dark else MUTED_NAVY

    card = Image.new("RGBA", (CARD_W, CARD_H), bg + (255,))
    draw = ImageDraw.Draw(card)

    # ----- right: QR + download CTA (layout first — sets lockup width limit) -----
    qr_dark_color = WHITE if dark else NAVY
    qr_light_color = NAVY if dark else WHITE
    QR_SIZE = 360
    qr_x = CARD_W - MARGIN - QR_SIZE
    sub_y = CARD_H - MARGIN - 16
    url_y = sub_y - 26
    qr_y = url_y - 14 - QR_SIZE
    cta_y = qr_y - 36

    # ----- top-left: hex + STANCEPRO + BY JC KRAFT (horizontal, 20% smaller) -----
    logo_path = LOGO_DARK if dark else LOGO_LIGHT
    logo = Image.open(logo_path).convert("RGBA")

    HEX_H = int(round(150 * LOCKUP_SIZE_SCALE * BACK_LOCKUP_SCALE))
    LOCKUP_CENTER_Y = MARGIN + HEX_H // 2
    hex_bbox = paste_logo_content_left(card, logo, MARGIN, HEX_H, LOCKUP_CENTER_Y)

    WM_BACK_H = wm_v5.wordmark_height_for_hex_bbox(hex_bbox, Path(logo_path))
    max_wm_w = max(50, qr_x - hex_bbox[2] - LOCKUP_GAP)
    wordmark = wm_v5.render_wordmark(dark=dark, target_h=WM_BACK_H, max_w=max_wm_w)
    wm_bbox = wm_v5.paste_wordmark(card, wordmark, hex_bbox[2] + LOCKUP_GAP, LOCKUP_CENTER_Y)

    by_font = load_font(FONT_AVENIR, 16, AV_MED)
    draw_letterspaced(draw, (wm_bbox[0], wm_bbox[3] + 8), "BY JC KRAFT", by_font, muted, extra_spacing_px=4)

    qr_img = make_qr(SMART_DOWNLOAD_URL, QR_SIZE, qr_dark_color, qr_light_color)
    card.paste(qr_img, (qr_x, qr_y), qr_img)

    # CTA: "DOWNLOAD THE APP" above the QR
    cta_font = load_font(FONT_AVENIR, 18, AV_BOLD)
    cta_text = "DOWNLOAD THE APP"
    cta_w = draw.textlength(cta_text, font=cta_font) + (len(cta_text) - 1) * 3
    cta_x = qr_x + (QR_SIZE - int(cta_w)) // 2
    draw_letterspaced(draw, (cta_x, cta_y), cta_text, cta_font, accent, extra_spacing_px=3)

    # URL under QR
    url_font = load_font(FONT_AVENIR, 18, AV_MED)
    url_text = "stance-pro.com/d"
    url_w = draw.textlength(url_text, font=url_font)
    url_x = qr_x + (QR_SIZE - int(url_w)) // 2
    draw.text((url_x, url_y), url_text, font=url_font, fill=fg)

    # Tiny "iOS · Android" supporting line
    sub_font = load_font(FONT_AVENIR, 14, AV_MED)
    sub_text = "iOS  ·  ANDROID"
    sub_w = draw.textlength(sub_text, font=sub_font) + (len(sub_text) - 1) * 2
    sub_x = qr_x + (QR_SIZE - int(sub_w)) // 2
    draw_letterspaced(draw, (sub_x, sub_y), sub_text, sub_font, muted, extra_spacing_px=2)

    return card.convert("RGB")


# ---------------- composite preview ----------------

def render_preview(front: Image.Image, back: Image.Image, gap: int = 60, pad: int = 60) -> Image.Image:
    """Side-by-side preview of front and back on a neutral grey backdrop."""
    backdrop = (235, 235, 233)
    total_w = pad * 2 + front.width + gap + back.width
    total_h = pad * 2 + front.height
    out = Image.new("RGB", (total_w, total_h), backdrop)

    # soft shadow under each card
    def paste_with_shadow(card_img: Image.Image, x: int, y: int):
        shadow = Image.new("RGBA", (card_img.width + 24, card_img.height + 24), (0, 0, 0, 0))
        sd = ImageDraw.Draw(shadow)
        sd.rectangle((12, 16, shadow.width - 12, shadow.height - 8), fill=(0, 0, 0, 35))
        out.paste(shadow, (x - 12, y - 12), shadow)
        out.paste(card_img, (x, y))

    paste_with_shadow(front, pad, pad)
    paste_with_shadow(back, pad + front.width + gap, pad)
    return out


# ---------------- main ----------------

def main() -> None:
    # backs (same for everyone, light + dark)
    back_light = render_back(dark=False)
    back_dark = render_back(dark=True)
    back_light.save(OUT_DIR / "back_light.png", dpi=(DPI, DPI))
    back_dark.save(OUT_DIR / "back_dark.png", dpi=(DPI, DPI))
    print("saved: back_light.png, back_dark.png")

    # per-person fronts + side-by-side previews
    for p in PEOPLE:
        for theme, back in (("light", back_light), ("dark", back_dark)):
            front = render_front(p, dark=(theme == "dark"))
            front_name = f"{p.slug}_{theme}_front.png"
            front.save(OUT_DIR / front_name, dpi=(DPI, DPI))

            preview = render_preview(front, back)
            preview_name = f"{p.slug}_{theme}_preview.png"
            preview.save(OUT_DIR / preview_name, dpi=(150, 150))
            print(f"saved: {front_name}, {preview_name}")


if __name__ == "__main__":
    main()
